version: '3.8'
services:
  mongo-toku:
    container_name: mongodb-toku
    image: mongo:4.4.29
    ports:
      - "28000:27017"
    volumes:
      - mongodata:/data/db1
  app:
    container_name: myapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo-toku
    environment:
      DB_HOST: mongo-toku:27017 
      PORT: 3000
      NODE_ENV: development
volumes:
  mongodata:
